import { Community, Post, Comment, Thread, Message, Profile } from '@/types';

export const MOCK_COMMUNITIES: Community[] = [
  {
    id: 'c1',
    creator_id: 'u1',
    name: 'Fitness with Alex',
    description: 'Transform your body and mind with expert-led workouts, nutrition plans, and daily motivation. Join 2,400+ members on their fitness journey.',
    cover_url: 'https://picsum.photos/seed/fitness/800/400',
    avatar_url: 'https://picsum.photos/seed/alex/100/100',
    monthly_price: 19.99,
    one_time_price: 149.99,
    member_count: 2418,
    post_count: 142,
    creator: { id: 'u1', name: 'Alex Rivera', image: 'https://picsum.photos/seed/alex/100/100' },
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: 'c2',
    creator_id: 'u2',
    name: 'Tech Insider',
    description: 'Deep dives into emerging tech, AI breakthroughs, and startup strategies. Weekly exclusive reports and live Q&As with industry leaders.',
    cover_url: 'https://picsum.photos/seed/tech/800/400',
    avatar_url: 'https://picsum.photos/seed/techavatar/100/100',
    monthly_price: 29.99,
    one_time_price: 249.99,
    member_count: 5832,
    post_count: 287,
    creator: { id: 'u2', name: 'Jordan Kim', image: 'https://picsum.photos/seed/jordan/100/100' },
    created_at: '2023-11-20T10:00:00Z',
  },
  {
    id: 'c3',
    creator_id: 'u3',
    name: 'Creative Studio',
    description: 'Unlock your creative potential with tutorials, critiques, and a supportive community of artists, designers, and photographers.',
    cover_url: 'https://picsum.photos/seed/creative/800/400',
    avatar_url: 'https://picsum.photos/seed/creativeavatar/100/100',
    monthly_price: 14.99,
    one_time_price: 99.99,
    member_count: 1204,
    post_count: 98,
    creator: { id: 'u3', name: 'Maya Chen', image: 'https://picsum.photos/seed/maya/100/100' },
    created_at: '2024-03-01T10:00:00Z',
  },
];

export const MOCK_POSTS: Post[] = [
  // Fitness with Alex
  {
    id: 'p1',
    community_id: 'c1',
    creator_id: 'u1',
    title: '30-Day Transformation Challenge Kickoff',
    body: 'Welcome to the 30-day challenge! Today we start with a full-body assessment. Watch the video for your baseline workout and nutrition guidelines.',
    type: 'video',
    media_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnail_url: 'https://picsum.photos/seed/workout1/800/450',
    is_exclusive: false,
    like_count: 342,
    comment_count: 87,
    liked_by_me: false,
    locked: false,
    creator: { id: 'u1', name: 'Alex Rivera', image: 'https://picsum.photos/seed/alex/100/100' },
    created_at: '2024-06-10T08:00:00Z',
  },
  {
    id: 'p2',
    community_id: 'c1',
    creator_id: 'u1',
    title: 'Morning Motivation Podcast — Episode 12',
    body: 'This week we talk about building sustainable habits and why most people fail at fitness goals. Tune in for actionable strategies.',
    type: 'audio',
    media_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    is_exclusive: true,
    like_count: 198,
    comment_count: 34,
    liked_by_me: true,
    locked: false,
    creator: { id: 'u1', name: 'Alex Rivera', image: 'https://picsum.photos/seed/alex/100/100' },
    created_at: '2024-06-09T07:00:00Z',
  },
  {
    id: 'p3',
    community_id: 'c1',
    creator_id: 'u1',
    title: 'Meal Prep Sunday — High Protein Edition',
    body: 'Here\'s my complete meal prep for the week. 5 meals, 150g protein per day, under $60 total. Full macros in the caption.',
    type: 'image',
    media_url: 'https://picsum.photos/seed/mealprep/800/600',
    is_exclusive: false,
    like_count: 521,
    comment_count: 112,
    liked_by_me: false,
    locked: false,
    creator: { id: 'u1', name: 'Alex Rivera', image: 'https://picsum.photos/seed/alex/100/100' },
    created_at: '2024-06-08T12:00:00Z',
  },
  {
    id: 'p4',
    community_id: 'c1',
    creator_id: 'u1',
    title: 'LIVE: Q&A — Ask Me Anything About Nutrition',
    body: 'Join me live for an open Q&A session. Bring your nutrition questions, supplement queries, and anything fitness-related!',
    type: 'live',
    is_exclusive: true,
    like_count: 89,
    comment_count: 203,
    liked_by_me: false,
    locked: true,
    creator: { id: 'u1', name: 'Alex Rivera', image: 'https://picsum.photos/seed/alex/100/100' },
    created_at: '2024-06-07T18:00:00Z',
  },
  {
    id: 'p5',
    community_id: 'c1',
    creator_id: 'u1',
    title: 'The Science of Progressive Overload',
    body: 'Progressive overload is the single most important principle in strength training. In this post I break down exactly how to implement it for maximum gains without injury. Start with a 5-10% increase in weight or reps each week...',
    type: 'text',
    is_exclusive: false,
    like_count: 267,
    comment_count: 45,
    liked_by_me: false,
    locked: false,
    creator: { id: 'u1', name: 'Alex Rivera', image: 'https://picsum.photos/seed/alex/100/100' },
    created_at: '2024-06-06T09:00:00Z',
  },
  // Tech Insider
  {
    id: 'p6',
    community_id: 'c2',
    creator_id: 'u2',
    title: 'GPT-5 Deep Dive: What Changed Everything',
    body: 'After two weeks of testing, here\'s my comprehensive breakdown of GPT-5\'s capabilities, limitations, and what it means for developers.',
    type: 'video',
    media_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnail_url: 'https://picsum.photos/seed/aitech/800/450',
    is_exclusive: true,
    like_count: 1203,
    comment_count: 342,
    liked_by_me: false,
    locked: false,
    creator: { id: 'u2', name: 'Jordan Kim', image: 'https://picsum.photos/seed/jordan/100/100' },
    created_at: '2024-06-10T10:00:00Z',
  },
  {
    id: 'p7',
    community_id: 'c2',
    creator_id: 'u2',
    title: 'Startup Funding Report — Q2 2024',
    body: 'Exclusive analysis of Q2 2024 venture capital trends. AI infrastructure dominates, but there\'s a surprising resurgence in biotech.',
    type: 'text',
    is_exclusive: true,
    like_count: 876,
    comment_count: 156,
    liked_by_me: false,
    locked: true,
    creator: { id: 'u2', name: 'Jordan Kim', image: 'https://picsum.photos/seed/jordan/100/100' },
    created_at: '2024-06-09T11:00:00Z',
  },
  {
    id: 'p8',
    community_id: 'c2',
    creator_id: 'u2',
    title: 'Inside Apple\'s AI Strategy',
    body: 'Exclusive photos from WWDC 2024 and my analysis of Apple\'s on-device AI approach.',
    type: 'image',
    media_url: 'https://picsum.photos/seed/apple2024/800/600',
    is_exclusive: false,
    like_count: 2341,
    comment_count: 489,
    liked_by_me: true,
    locked: false,
    creator: { id: 'u2', name: 'Jordan Kim', image: 'https://picsum.photos/seed/jordan/100/100' },
    created_at: '2024-06-08T14:00:00Z',
  },
  {
    id: 'p9',
    community_id: 'c2',
    creator_id: 'u2',
    title: 'Tech Weekly Podcast — The AI Arms Race',
    body: 'This week: OpenAI vs Google vs Anthropic. Who\'s winning and what it means for your business.',
    type: 'audio',
    media_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    is_exclusive: false,
    like_count: 654,
    comment_count: 98,
    liked_by_me: false,
    locked: false,
    creator: { id: 'u2', name: 'Jordan Kim', image: 'https://picsum.photos/seed/jordan/100/100' },
    created_at: '2024-06-07T09:00:00Z',
  },
  {
    id: 'p10',
    community_id: 'c2',
    creator_id: 'u2',
    title: 'LIVE: Breaking Down the Latest AI Announcements',
    body: 'Live reaction and analysis of today\'s major AI announcements. Join the conversation!',
    type: 'live',
    is_exclusive: true,
    like_count: 432,
    comment_count: 876,
    liked_by_me: false,
    locked: true,
    creator: { id: 'u2', name: 'Jordan Kim', image: 'https://picsum.photos/seed/jordan/100/100' },
    created_at: '2024-06-06T16:00:00Z',
  },
  // Creative Studio
  {
    id: 'p11',
    community_id: 'c3',
    creator_id: 'u3',
    title: 'Mastering Light in Portrait Photography',
    body: 'Light is everything. In this tutorial I walk through 5 lighting setups you can achieve with a single speedlight.',
    type: 'image',
    media_url: 'https://picsum.photos/seed/portrait/800/600',
    is_exclusive: false,
    like_count: 445,
    comment_count: 67,
    liked_by_me: false,
    locked: false,
    creator: { id: 'u3', name: 'Maya Chen', image: 'https://picsum.photos/seed/maya/100/100' },
    created_at: '2024-06-10T09:00:00Z',
  },
  {
    id: 'p12',
    community_id: 'c3',
    creator_id: 'u3',
    title: 'Figma to Reality: My Design Process',
    body: 'Full walkthrough of how I take a concept from sketch to polished Figma prototype to final product.',
    type: 'video',
    media_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnail_url: 'https://picsum.photos/seed/design/800/450',
    is_exclusive: true,
    like_count: 312,
    comment_count: 54,
    liked_by_me: false,
    locked: true,
    creator: { id: 'u3', name: 'Maya Chen', image: 'https://picsum.photos/seed/maya/100/100' },
    created_at: '2024-06-09T13:00:00Z',
  },
  {
    id: 'p13',
    community_id: 'c3',
    creator_id: 'u3',
    title: 'Color Theory for Digital Artists',
    body: 'Understanding color relationships is the foundation of great design. Here\'s my complete guide to color theory applied to digital art and UI design.',
    type: 'text',
    is_exclusive: false,
    like_count: 567,
    comment_count: 89,
    liked_by_me: true,
    locked: false,
    creator: { id: 'u3', name: 'Maya Chen', image: 'https://picsum.photos/seed/maya/100/100' },
    created_at: '2024-06-08T10:00:00Z',
  },
  {
    id: 'p14',
    community_id: 'c3',
    creator_id: 'u3',
    title: 'Creative Conversations Podcast — Ep. 8',
    body: 'This week I chat with award-winning illustrator Sam Park about finding your artistic voice.',
    type: 'audio',
    media_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    is_exclusive: false,
    like_count: 234,
    comment_count: 41,
    liked_by_me: false,
    locked: false,
    creator: { id: 'u3', name: 'Maya Chen', image: 'https://picsum.photos/seed/maya/100/100' },
    created_at: '2024-06-07T11:00:00Z',
  },
  {
    id: 'p15',
    community_id: 'c3',
    creator_id: 'u3',
    title: 'LIVE: Portfolio Review Session',
    body: 'Submit your work for live critique! I\'ll be reviewing portfolios and giving actionable feedback.',
    type: 'live',
    is_exclusive: true,
    like_count: 178,
    comment_count: 312,
    liked_by_me: false,
    locked: true,
    creator: { id: 'u3', name: 'Maya Chen', image: 'https://picsum.photos/seed/maya/100/100' },
    created_at: '2024-06-06T15:00:00Z',
  },
];

export const MOCK_COMMENTS: Comment[] = [
  {
    id: 'cm1',
    post_id: 'p1',
    user_id: 'u4',
    body: 'This is exactly what I needed to get started! The baseline workout was challenging but doable.',
    like_count: 12,
    user: { id: 'u4', name: 'Sarah M.', image: 'https://picsum.photos/seed/sarah/100/100' },
    created_at: '2024-06-10T09:30:00Z',
  },
  {
    id: 'cm2',
    post_id: 'p1',
    user_id: 'u5',
    body: 'Day 1 complete! Already feeling the burn. Can\'t wait to see the results in 30 days 💪',
    like_count: 8,
    user: { id: 'u5', name: 'Mike T.', image: 'https://picsum.photos/seed/mike/100/100' },
    created_at: '2024-06-10T10:15:00Z',
  },
  {
    id: 'cm3',
    post_id: 'p1',
    user_id: 'u6',
    body: 'Alex, what\'s the recommended rest time between sets for beginners?',
    like_count: 5,
    user: { id: 'u6', name: 'Emma L.', image: 'https://picsum.photos/seed/emma/100/100' },
    created_at: '2024-06-10T11:00:00Z',
  },
  {
    id: 'cm4',
    post_id: 'p1',
    user_id: 'u7',
    body: 'Been following Alex for 6 months and the results are incredible. Best investment I\'ve made.',
    like_count: 24,
    user: { id: 'u7', name: 'Chris P.', image: 'https://picsum.photos/seed/chris/100/100' },
    created_at: '2024-06-10T12:00:00Z',
  },
];

export const MOCK_THREADS: Thread[] = [
  {
    id: 't1',
    other_user: { id: 'u1', name: 'Alex Rivera', image: 'https://picsum.photos/seed/alex/100/100' },
    last_message: 'Thanks for joining! Let me know if you have any questions about the program.',
    last_message_at: '2024-06-10T14:30:00Z',
    unread_count: 2,
  },
  {
    id: 't2',
    other_user: { id: 'u2', name: 'Jordan Kim', image: 'https://picsum.photos/seed/jordan/100/100' },
    last_message: 'The Q2 report is dropping tomorrow — you\'re going to love it.',
    last_message_at: '2024-06-09T18:00:00Z',
    unread_count: 0,
  },
  {
    id: 't3',
    other_user: { id: 'u3', name: 'Maya Chen', image: 'https://picsum.photos/seed/maya/100/100' },
    last_message: 'Your portfolio submission was great! I\'ll feature it in the next review.',
    last_message_at: '2024-06-08T11:00:00Z',
    unread_count: 1,
  },
  {
    id: 't4',
    other_user: { id: 'u8', name: 'David Park', image: 'https://picsum.photos/seed/david/100/100' },
    last_message: 'Did you catch the live stream yesterday?',
    last_message_at: '2024-06-07T20:00:00Z',
    unread_count: 0,
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'm1',
    sender_id: 'u1',
    recipient_id: 'me',
    body: 'Hey! Welcome to Fitness with Alex. I\'m so glad you joined.',
    created_at: '2024-06-10T14:00:00Z',
  },
  {
    id: 'm2',
    sender_id: 'me',
    recipient_id: 'u1',
    body: 'Thanks Alex! Really excited to start the 30-day challenge.',
    created_at: '2024-06-10T14:10:00Z',
  },
  {
    id: 'm3',
    sender_id: 'u1',
    recipient_id: 'me',
    body: 'You\'re going to crush it! Make sure to track your baseline measurements before starting.',
    created_at: '2024-06-10T14:20:00Z',
  },
  {
    id: 'm4',
    sender_id: 'me',
    recipient_id: 'u1',
    body: 'Will do! Quick question — should I do the workout in the morning or evening?',
    created_at: '2024-06-10T14:25:00Z',
  },
  {
    id: 'm5',
    sender_id: 'u1',
    recipient_id: 'me',
    body: 'Thanks for joining! Let me know if you have any questions about the program.',
    created_at: '2024-06-10T14:30:00Z',
  },
];

export const MOCK_PROFILE: Profile = {
  id: 'me',
  username: 'You',
  bio: 'Passionate about fitness, tech, and creativity. Member of 3 amazing communities.',
  avatar_url: 'https://picsum.photos/seed/myprofile/100/100',
  cover_url: 'https://picsum.photos/seed/mycover/800/400',
  is_creator: false,
  follower_count: 0,
  created_at: '2024-01-01T00:00:00Z',
};

export const MOCK_CREATOR_PROFILES: Record<string, Profile> = {
  u1: {
    id: 'u1',
    username: 'Alex Rivera',
    bio: 'Certified personal trainer & nutritionist. Helping 2,400+ members transform their lives through fitness.',
    avatar_url: 'https://picsum.photos/seed/alex/100/100',
    cover_url: 'https://picsum.photos/seed/alexcover/800/400',
    is_creator: true,
    follower_count: 48200,
    created_at: '2024-01-15T10:00:00Z',
  },
  u2: {
    id: 'u2',
    username: 'Jordan Kim',
    bio: 'Tech journalist & startup advisor. Former Google engineer. Breaking down the future of technology.',
    avatar_url: 'https://picsum.photos/seed/jordan/100/100',
    cover_url: 'https://picsum.photos/seed/jordancover/800/400',
    is_creator: true,
    follower_count: 125000,
    created_at: '2023-11-20T10:00:00Z',
  },
  u3: {
    id: 'u3',
    username: 'Maya Chen',
    bio: 'Award-winning designer & photographer. Teaching creative skills to 1,200+ students worldwide.',
    avatar_url: 'https://picsum.photos/seed/maya/100/100',
    cover_url: 'https://picsum.photos/seed/mayacover/800/400',
    is_creator: true,
    follower_count: 32800,
    created_at: '2024-03-01T10:00:00Z',
  },
};

export function timeAgo(dateString: string): string {
  const date = new Date(dateString);
  const now = new Date();
  const seconds = Math.floor((now.getTime() - date.getTime()) / 1000);
  if (seconds < 60) return 'just now';
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  if (days < 7) return `${days}d ago`;
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
}

export function formatCount(n: number): string {
  if (n >= 1000000) return `${(n / 1000000).toFixed(1)}M`;
  if (n >= 1000) return `${(n / 1000).toFixed(1)}k`;
  return String(n);
}
